version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      # address host:address container
      - "5672:5672"   # the port RabbitMQ will listen on. Same port in-container and out-container.
      - "8081:15672"  # the port the dashboard web service will be available from

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGODB=mongodb://mongo
    volumes:
      - "/logs:/logs"
