@startuml
[*] -left-> WAITING
WAITING -up-> CREATE: create msg
CREATE --> WAITING: new lobby or error
WAITING -left-> JOIN: join msg
JOIN --> WAITING: updated lobby or error
WAITING -right-> LEAVE: leave msg
LEAVE--> WAITING: updated lobby or error
WAITING -down-> START: start msg
START--> WAITING: gameID or error
@enduml